ALTER TABLE APP.OFFICES ALTER COLUMN OFFICE_CODE NOT NULL;
ALTER TABLE APP.OFFICES ADD PRIMARY KEY (OFFICE_CODE);

ALTER TABLE APP.EMPLOYEES ALTER COLUMN EMPLOYEE_NUMBER NOT NULL;
ALTER TABLE APP.EMPLOYEES ADD PRIMARY KEY (EMPLOYEE_NUMBER);

ALTER TABLE APP.CUSTOMERS ALTER COLUMN CUSTOMER_NUMBER NOT NULL;
ALTER TABLE APP.CUSTOMERS ADD PRIMARY KEY (CUSTOMER_NUMBER);

ALTER TABLE APP.ORDERS ALTER COLUMN ORDER_NUMBER NOT NULL;
ALTER TABLE APP.ORDERS ADD PRIMARY KEY (ORDER_NUMBER);

ALTER TABLE APP.PRODUCTS ALTER COLUMN PRODUCT_CODE NOT NULL;
ALTER TABLE APP.PRODUCTS ADD PRIMARY KEY (PRODUCT_CODE);

ALTER TABLE APP.PAYMENTS ALTER COLUMN CUSTOMER_NUMBER NOT NULL;
ALTER TABLE APP.PAYMENTS ALTER COLUMN CHECK_NUMBER NOT NULL;
ALTER TABLE APP.PAYMENTS ADD PRIMARY KEY (CUSTOMER_NUMBER, CHECK_NUMBER);

ALTER TABLE APP.ORDER_DETAILS ALTER COLUMN ORDER_NUMBER NOT NULL;
ALTER TABLE APP.ORDER_DETAILS ALTER COLUMN ORDER_LINE_NUMBER NOT NULL;
ALTER TABLE APP.ORDER_DETAILS ADD PRIMARY KEY (ORDER_NUMBER,ORDER_LINE_NUMBER);

ALTER TABLE APP.EMPLOYEES
ADD CONSTRAINT FK_EMP_OFF
  FOREIGN KEY (OFFICE_CODE) REFERENCES OFFICES (OFFICE_CODE);


ALTER TABLE APP.ORDER_DETAILS
  ADD CONSTRAINT FK_ORDDET_PROD
    FOREIGN KEY (PRODUCT_CODE) REFERENCES PRODUCTS (PRODUCT_CODE);

ALTER TABLE APP.ORDER_DETAILS
  ADD CONSTRAINT FK_ORDDET_ORD
    FOREIGN KEY (ORDER_NUMBER) REFERENCES ORDERS (ORDER_NUMBER);



ALTER TABLE APP.CUSTOMERS
ADD FOREIGN KEY (SALES_REP_EMPLOYEE_NUMBER) REFERENCES EMPLOYEES (EMPLOYEE_NUMBER);

ALTER TABLE APP.ORDERS
ADD FOREIGN KEY (CUSTOMER_NUMBER) REFERENCES CUSTOMERS (CUSTOMER_NUMBER);


ALTER TABLE APP.PRODUCT_LINES ALTER COLUMN PRODUCT_LINE NOT NULL;
ALTER TABLE APP.PRODUCT_LINES ADD PRIMARY KEY (PRODUCT_LINE);

ALTER TABLE APP.PRODUCTS
ADD constraint fk_prod_prodline FOREIGN KEY (PRODUCT_LINE) REFERENCES PRODUCT_LINES (PRODUCT_LINE);

