CREATE TABLE CUSTOMERS
(
    CUSTOMER_NUMBER INT,
    CUSTOMER_NAME VARCHAR(50),
    CONTACT_LAST_NAME VARCHAR(50),
    CONTACT_FIRST_NAME VARCHAR(50),
    PHONE VARCHAR(50),
    ADDRESS_LINE1 VARCHAR(50),
    ADDRESS_LINE2 VARCHAR(50),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    POSTAL_CODE VARCHAR(15),
    COUNTRY VARCHAR(50),
    SALES_REP_EMPLOYEE_NUMBER INT,
    CREDIT_LIMIT FLOAT(52)
);
CREATE TABLE EMPLOYEES
(
    EMPLOYEE_NUMBER INT,
    LAST_NAME VARCHAR(50),
    FIRST_NAME VARCHAR(50),
    EXTENSION VARCHAR(10),
    EMAIL VARCHAR(100),
    OFFICE_CODE VARCHAR(10),
    REPORTS_TO INT,
    JOB_TITLE VARCHAR(50)
);
CREATE TABLE OFFICES
(
    OFFICE_CODE VARCHAR(10),
    CITY VARCHAR(50),
    PHONE VARCHAR(50),
    ADDRESS_LINE1 VARCHAR(50),
    ADDRESS_LINE2 VARCHAR(50),
    STATE VARCHAR(50),
    COUNTRY VARCHAR(50),
    POSTAL_CODE VARCHAR(15),
    TERRITORY VARCHAR(10)
);
CREATE TABLE ORDER_DETAILS
(
    ORDER_NUMBER INT,
    PRODUCT_CODE VARCHAR(15),
    QUANTITY_ORDERED INT,
    PRICE_EACH FLOAT(52),
    ORDER_LINE_NUMBER SMALLINT
);
CREATE TABLE ORDERS
(
    ORDER_NUMBER INT,
    ORDER_DATE DATE,
    REQUIRED_DATE DATE,
    SHIPPED_DATE DATE,
    STATUS VARCHAR(15),
    COMMENTS LONG VARCHAR,
    CUSTOMER_NUMBER INT
);
CREATE TABLE PAYMENTS
(
    CUSTOMER_NUMBER INT,
    CHECK_NUMBER VARCHAR(50),
    PAYMENT_DATE DATE,
    AMOUNT FLOAT(52)
);
CREATE TABLE PRODUCT_LINES
(
    PRODUCT_LINE VARCHAR(50),
    TEXT_DESCRIPTION VARCHAR(4000)
);
CREATE TABLE PRODUCTS
(
    PRODUCT_CODE VARCHAR(15),
    PRODUCT_NAME VARCHAR(70),
    PRODUCT_LINE VARCHAR(50),
    PRODUCT_SCALE VARCHAR(10),
    PRODUCT_VENDOR VARCHAR(50),
    PRODUCT_DESCRIPTION LONG VARCHAR,
    QUANTITY_IN_STOCK INT,
    BUY_PRICE FLOAT(52),
    MSRP FLOAT(52)
);
CREATE UNIQUE INDEX CUSTOMERS_PK ON CUSTOMERS (CUSTOMER_NUMBER);
CREATE UNIQUE INDEX EMPLOYEES_PK ON EMPLOYEES (EMPLOYEE_NUMBER);
CREATE UNIQUE INDEX OFFICES_PK ON OFFICES (OFFICE_CODE);
CREATE UNIQUE INDEX ORDER_DETAILS_PK ON ORDER_DETAILS (ORDER_NUMBER, PRODUCT_CODE);
CREATE UNIQUE INDEX ORDERS_PK ON ORDERS (ORDER_NUMBER);
CREATE INDEX ORDERS_CUTOMER ON ORDERS (CUSTOMER_NUMBER);
CREATE UNIQUE INDEX PAYMENTS_PK ON PAYMENTS (CUSTOMER_NUMBER, CHECK_NUMBER);
CREATE UNIQUE INDEX PRODUCT_LINES_PK ON PRODUCT_LINES (PRODUCT_LINE);
CREATE UNIQUE INDEX PRODUCTS_PK ON PRODUCTS (PRODUCT_CODE);
