INSERT INTO "APP"."OFFICE_TYPES" (OFFICE_TYPE,DESCRIPTION) VALUES (1,'Headquarters');
INSERT INTO "APP"."OFFICE_TYPES" (OFFICE_TYPE,DESCRIPTION) VALUES (2,'Regional');
INSERT INTO "APP"."OFFICE_TYPES" (OFFICE_TYPE,DESCRIPTION) VALUES (3,'Local');

